- name: Pacman_App_Sync
  hosts: all
  tasks:
    - name: Loop through target clusters for AKS Clusters
      ansible.builtin.include_tasks: aks_details.yml        
      with_items: "{{ target_clusters }}"
      when:
        - "aks in item|lower"
    - name: Retrieve the details for GSLB_DOMAIN
      community.aws.route53:
        state: get
        zone: "{{ base_domain }}"
        record: "{{ gslb_domain }}"
        type: A
      register: record
    # - name: Delete Old Ingress/Route
    #   community.aws.route53:
    #     state: absent
    #     zone: foo.com
    #     record: "{{ rec.set.record }}"
    #     ttl: "{{ rec.set.ttl }}"
    #     type: "{{ rec.set.type }}"
    #     value: "{{ rec.set.value }}"


