- name: Hello World Sample
  hosts: all
  tasks:
    - name: Loop through target clusters
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ target_clusters }}"
    - name: Import Role
      ansible.builtin.include_role:
        role: manage_aws_r53
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'CLIENT_ID') }}'"
    - name: Azure Login
      ansible.builtin.shell: |
        az login --service-principal -u "{{ lookup('ansible.builtin.env', 'CLIENT_ID') }}" -p "{{ lookup('ansible.builtin.env', 'PASSWORD') }}" --tenant "{{ lookup('ansible.builtin.env', 'TENANT') }}"
